/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { parseRoutes } from 'bwcx-client-vue3';


const clientRoutes = parseRoutes([
  {
    name: 'About',
    path: '/about',
    fullPath: '/about',
    component: () => import(/* webpackChunkName: "About" */ '../modules/about/about.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'DemoDetail',
    path: '/demo',
    fullPath: '/demo',
    component: () => import(/* webpackChunkName: "DemoDetail" */ '../modules/demo/demo-detail.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'Home',
    path: '/',
    fullPath: '/',
    component: () => import(/* webpackChunkName: "Home" */ '../modules/home/home.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'Releases',
    path: '/releases',
    fullPath: '/releases',
    component: () => import(/* webpackChunkName: "Releases" */ '../modules/releases/releases.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
]);

export default clientRoutes;

